-- STEP 1: CREATE CHANNELS TABLE
create table public.channels (
  id bigint generated by default as identity primary key,
  name text not null unique,
  avatar_path text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.channels enable row level security;

create policy "Channels are viewable by everyone"
  on public.channels for select
  using (true);

-- STEP 2: ADD METRICS TO VIDEOS TABLE
alter table public.videos 
add column if not exists likes bigint default 0,
add column if not exists dislikes bigint default 0,
add column if not exists views bigint default 0,
add column if not exists avg_watch_duration_seconds float default 0;

-- STEP 3: ADD CHANNEL_ID TO VIDEOS TABLE
alter table public.videos 
add column if not exists channel_id bigint references public.channels(id) on delete set null;

-- STEP 4: CREATE VIDEO ENGAGEMENT TABLE
create table if not exists public.video_engagement (
  id bigint generated by default as identity primary key,
  video_id bigint references public.videos(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  watched_duration_seconds float default 0,
  is_liked boolean default false,
  is_disliked boolean default false,
  watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(video_id, user_id)
);

alter table public.video_engagement enable row level security;

-- STEP 5: EXTEND PROFILES TABLE
alter table public.profiles 
add column if not exists parent_email text,
add column if not exists total_watch_time_seconds bigint default 0,
add column if not exists last_active timestamp with time zone;

-- STEP 6: CREATE/UPDATE USERS TABLE
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_login timestamp with time zone,
  total_profiles int default 0,
  total_watch_time_seconds bigint default 0
);

-- DISABLE RLS ON USERS TABLE - Authorization handled in admin panel
alter table public.users disable row level security;

-- STEP 7: CREATE AUTH TRIGGER
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, is_admin, created_at)
  values (new.id, new.email, false, now())
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- STEP 8: SEED SAMPLE CHANNELS (OPTIONAL)
INSERT INTO public.channels (name, description) VALUES
('Educational Fun', 'Learning through play'),
('Adventure Stories', 'Exciting animated adventures'),
('Music & Rhymes', 'Songs and nursery rhymes'),
('Cartoons', 'Popular cartoon shows'),
('Science Explorations', 'Fun science experiments')
ON CONFLICT (name) DO NOTHING;
