-- CREATE MART TABLE (Shopping/Ads Section)
create table if not exists public.mart (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_path text not null,
  video_path text,
  price text,
  product_url text,
  is_active boolean default true,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for mart
alter table public.mart enable row level security;

-- RLS Policy: Everyone can read mart items
create policy "Mart items are viewable by everyone"
  on public.mart for select
  using (true);
