-- =====================================================
-- SQL UPDATES FOR KIDSAPP
-- =====================================================

-- 1. ADD CHANNELS TABLE
create table public.channels (
  id bigint generated by default as identity primary key,
  name text not null unique,
  avatar_path text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for channels
alter table public.channels enable row level security;

-- RLS Policy: Everyone can read channels
create policy "Channels are viewable by everyone"
  on public.channels for select
  using (true);

-- 2. ADD METRICS COLUMNS TO VIDEOS TABLE
alter table public.videos 
add column if not exists likes bigint default 0,
add column if not exists dislikes bigint default 0,
add column if not exists views bigint default 0,
add column if not exists avg_watch_duration_seconds float default 0;

-- 3. UPDATE VIDEOS TABLE - Add channel_id foreign key (optional, can use channel_name or both)
-- First add the column
alter table public.videos 
add column if not exists channel_id bigint references public.channels(id) on delete set null;

-- 4. CREATE VIDEO ENGAGEMENT TABLE (for tracking individual user engagements)
create table if not exists public.video_engagement (
  id bigint generated by default as identity primary key,
  video_id bigint references public.videos(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  watched_duration_seconds float default 0,
  is_liked boolean default false,
  is_disliked boolean default false,
  watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(video_id, user_id)
);

alter table public.video_engagement enable row level security;

-- 5. CREATE USER PROFILE TABLE (Extended for admin panel)
-- Note: This might already exist as 'profiles', so we'll add columns if needed
alter table public.profiles 
add column if not exists parent_email text,
add column if not exists total_watch_time_seconds bigint default 0,
add column if not exists last_active timestamp with time zone;

-- 6. EXTEND USERS TABLE (for admin panel to show more details)
-- Create users table if it doesn't exist (usually managed by Supabase Auth with a trigger)
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_login timestamp with time zone,
  total_profiles int default 0,
  total_watch_time_seconds bigint default 0
);

alter table public.users enable row level security;

create policy "Users can view their own record"
  on public.users for select
  using (auth.uid() = id or exists (
    select 1 from public.users where id = auth.uid() and is_admin = true
  ));

-- 7. CREATE AUTH TRIGGER to auto-create user record (if not already present)
-- This trigger should already exist, but here's the safe version
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, is_admin, created_at)
  values (new.id, new.email, false, now())
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Drop old trigger if exists and recreate
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =====================================================
-- SAMPLE DATA & MIGRATIONS
-- =====================================================

-- Add sample channels
INSERT INTO public.channels (name, description) VALUES
('Educational Fun', 'Learning through play'),
('Adventure Stories', 'Exciting animated adventures'),
('Music & Rhymes', 'Songs and nursery rhymes'),
('Cartoons', 'Popular cartoon shows'),
('Science Explorations', 'Fun science experiments')
ON CONFLICT (name) DO NOTHING;

-- =====================================================
-- NOTES FOR IMPLEMENTATION
-- =====================================================
-- 
-- 1. CHANNELS: 
--    - Dropdown in add video form to select channel instead of typing
--    - Channel management page in admin panel
--
-- 2. VIDEO METRICS:
--    - Views: increment when video is played
--    - Likes/Dislikes: increment from frontend when user likes/dislikes
--    - Avg Watch Duration: calculated from video_engagement table
--
-- 3. ADMIN PANEL USERS TABLE:
--    - Show: Email, Is Admin, Created Date, Last Login, Total Profiles, Total Watch Time

-- =====================================================
-- CONTENT LEVEL CLEANUP (Preschool + Younger only)
-- =====================================================

-- Merge legacy video content levels into the remaining 2 options.
-- Run once in Supabase SQL editor.
update public.videos
set content_level = 'Younger'
where lower(coalesce(content_level, '')) in ('older', 'choose for me', 'chooseforme');

-- Merge legacy profile content types into the remaining 2 options.
update public.profiles
set content_type = 'Younger'
where lower(coalesce(content_type, '')) in ('older', 'choose for me', 'chooseforme');
--
-- 4. ADMIN PANEL VIDEOS:
--    - Show: Title, Views, Likes, Dislikes, Avg Watch Duration, Actions (Edit, Delete)
--    - Edit: Thumbnail, Avatar, Title, Channel, etc.
--
-- 5. VIDEO ENGAGEMENT:
--    - Track each user's interaction with each video
--    - Calculate aggregate metrics
