-- Users are managed by Supabase Auth (auth.users)

-- Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null, -- Store as Hex String (e.g., '0xFFFF0000') or Integer
  icon_path text -- Optional Bunny path (e.g., 'images/category_icons/icon.png')
);

-- Videos Table
create table public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  thumbnail_path text, -- Optional: Path in Bunny (e.g., 'images/thumbnails/abc.jpg')
  video_path text not null,     -- Path in Bunny (e.g., 'video/abc.mp4')
  duration text not null,       -- e.g., '2:30'
  content_level text, -- 'Preschool', 'Younger'
  channel_name text not null,
  channel_avatar_path text,     -- Optional Bunny path (e.g., 'images/avatars/avatar.png')
  is_shorts boolean not null default false,
  category_id bigint references public.categories(id)
);

-- Profiles Table (Kid Profiles linked to a Parent User)
create table public.profiles (
  id uuid default gen_random_uuid() primary key,
  parent_id uuid references auth.users(id) not null,
  name text not null,
  avatar_path text not null,    -- Path in Bunny (e.g., 'images/avatars/avatar1.png')
  age int not null,
  birth_month int, -- 1-12
  content_type text, -- 'Preschool', 'Younger'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Blocked Content Table (To store blocked channels/videos per profile)
create table public.blocked_content (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  item_id text not null,        -- video_id or channel_name
  item_type text not null,      -- 'video' or 'channel'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.categories enable row level security;
alter table public.videos enable row level security;
alter table public.profiles enable row level security;
alter table public.blocked_content enable row level security;

-- RLS Policies

-- Categories: Everyone can read
create policy "Public categories are viewable by everyone"
  on public.categories for select
  using ( true );

-- Videos: Everyone can read
create policy "Videos are viewable by everyone"
  on public.videos for select
  using ( true );

-- Profiles: Users can only see/edit their own kid profiles
create policy "Users can view own profiles"
  on public.profiles for select
  using ( auth.uid() = parent_id );

create policy "Users can insert own profiles"
  on public.profiles for insert
  with check ( auth.uid() = parent_id );

create policy "Users can update own profiles"
  on public.profiles for update
  using ( auth.uid() = parent_id );

create policy "Users can delete own profiles"
  on public.profiles for delete
  using ( auth.uid() = parent_id );

-- Blocked Content: Users can manage blocked content for their own profiles
create policy "Users can view blocked content for their profiles"
  on public.blocked_content for select
  using ( exists (
    select 1 from public.profiles
    where profiles.id = blocked_content.profile_id
    and profiles.parent_id = auth.uid()
  ));

create policy "Users can insert blocked content for their profiles"
  on public.blocked_content for insert
  with check ( exists (
    select 1 from public.profiles
    where profiles.id = blocked_content.profile_id
    and profiles.parent_id = auth.uid()
  ));

create policy "Users can delete blocked content for their profiles"
  on public.blocked_content for delete
  using ( exists (
    select 1 from public.profiles
    where profiles.id = blocked_content.profile_id
    and profiles.parent_id = auth.uid()
  ));

-- Initial Data Seeding (Optional - Example)
-- insert into public.categories (name, color) values ('Explore', '0xFFFFD600');
