-- 1. Storage Deletion Triggers
-- Function to delete from storage.objects
-- This assumes 'storage.objects' is available and deletable. 
-- In Supabase managed service, messing with storage.objects directly via SQL triggers on public tables is powerful but requires permissions.
CREATE OR REPLACE FUNCTION public.delete_video_assets()
RETURNS TRIGGER AS $$
BEGIN
  -- Delete video file if exists
  IF OLD.video_path IS NOT NULL THEN
    DELETE FROM storage.objects WHERE name = OLD.video_path;
  END IF;
  -- Delete thumbnail file if exists
  IF OLD.thumbnail_path IS NOT NULL THEN
    DELETE FROM storage.objects WHERE name = OLD.thumbnail_path;
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_video_delete ON public.videos;
CREATE TRIGGER on_video_delete
AFTER DELETE ON public.videos
FOR EACH ROW EXECUTE FUNCTION public.delete_video_assets();


-- 3. Mart Enhancements: Sub-link ads
CREATE TABLE IF NOT EXISTS public.mart_ads (
    id bigint generated by default as identity primary key,
    image_path text not null,
    link text,
    title text,
    is_active boolean default true,
    display_order int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.mart_ads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Ads are viewable by everyone" ON public.mart_ads;
CREATE POLICY "Ads are viewable by everyone" ON public.mart_ads FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage ads" ON public.mart_ads;
CREATE POLICY "Admins can manage ads" ON public.mart_ads FOR ALL USING (public.is_admin());


-- 4 & 6. Likes/Dislikes
CREATE TABLE IF NOT EXISTS public.video_likes (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    video_id bigint references public.videos(id) on delete cascade not null,
    is_like boolean not null, -- true = like, false = dislike
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    UNIQUE(user_id, video_id)
);

ALTER TABLE public.video_likes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users view own likes" ON public.video_likes;
CREATE POLICY "Users view own likes" ON public.video_likes FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users manage own likes" ON public.video_likes;
CREATE POLICY "Users manage own likes" ON public.video_likes FOR ALL USING (auth.uid() = user_id);


-- 14. Referrals
CREATE TABLE IF NOT EXISTS public.referrals (
    id bigint generated by default as identity primary key,
    referrer_id uuid references auth.users(id) not null,
    referred_email text not null,
    status text default 'pending', -- pending, completed
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users view own referrals" ON public.referrals;
CREATE POLICY "Users view own referrals" ON public.referrals FOR SELECT USING (auth.uid() = referrer_id);

DROP POLICY IF EXISTS "Users insert own referrals" ON public.referrals;
CREATE POLICY "Users insert own referrals" ON public.referrals FOR INSERT WITH CHECK (auth.uid() = referrer_id);

DROP POLICY IF EXISTS "Admins manage referrals" ON public.referrals;
CREATE POLICY "Admins manage referrals" ON public.referrals FOR ALL USING (public.is_admin());


-- 16. Reports
CREATE TABLE IF NOT EXISTS public.reports (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id), -- Can be null if anonymous? Better to track.
    video_id bigint references public.videos(id),
    reason text not null,
    description text,
    status text default 'open',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS response text;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS responded_at timestamp with time zone;

DROP POLICY IF EXISTS "Admins view reports" ON public.reports;
DROP POLICY IF EXISTS "Admins manage reports" ON public.reports;
CREATE POLICY "Admins manage reports" ON public.reports FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Users view own reports" ON public.reports;
CREATE POLICY "Users view own reports" ON public.reports FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users create reports" ON public.reports;
CREATE POLICY "Users create reports" ON public.reports FOR INSERT WITH CHECK (true);
